export const AlphabetWords = {
    A: ['Apple', 'Ant', 'Airplane', 'Arrow', 'Artist', 'Able', 'Arm', 'Aunt', 'Answer', 'Ape', 'Alert','Alpha'],
    B: ['Ball', 'Bear', 'Banana', 'Book', 'Balloon', 'Bee', 'Bird', 'Boat', 'Bell', 'Blue', 'Bunny','Blessed'],
    C: ['Cat', 'Christmas', 'Cake', 'Candy', 'Cabin', 'Cup', 'Car', 'Cloud', 'Corn', 'Cow', 'Coat','Chariot'],
    D: ['Dog', 'Door', 'Duck', 'Dolphin', 'Daddy', 'Drum', 'Deer', 'Desk', 'Doll', 'Dot', 'Dinner','Daystar'],
    E: ['Echo', 'Eagle', 'Egg', 'Eye', 'Earth', 'Ear', 'Elf', 'Elohim', 'East', 'End', 'Eat','Emmanuel'],
    F: ['Fish', 'Flower', 'Friend', 'Flag', 'Fire', 'Frog', 'Fork', 'Fan', 'Feet', 'Fox', 'Farm','Father'],
    G: ['Garment', 'Goat', 'Guitar', 'Glass', 'Garden', 'Game', 'Gift', 'Gold', 'Goose', 'Gum', 'Girl','Good'],
    H: ['Horse', 'House', 'Hat', 'Heart', 'Hand', 'Hippo', 'Hill', 'Horn', 'Home', 'Hug', 'Hair','Holy'],
    I: ['Ice', 'Island', 'Image', 'Ink', 'Iron', 'Igloo', 'Inch', 'Ivy', 'Item', 'Inner', 'Income','Instant'],
    J: ['Jam', 'Juice', 'Jockey', 'Jacket', 'Jungle', 'Jump', 'Jar', 'Jet', 'Joke', 'Joy', 'Jelly','Jesus'],
    K: ['King', 'Kite', 'Keyboard', 'Key', 'Kitchen', 'Kitten', 'Kid', 'Knee', 'Koala', 'Keep', 'Kind','Kingdom'],
    L: ['Lion', 'Lamp', 'Leaf', 'Lemon', 'Ladder', 'Lamb', 'Lake', 'Light', 'Lime', 'Log', 'Lunch','Laugh'],
    M: ['Moon', 'Mum', 'Mouse', 'Mango', 'Mind', 'Milk', 'Monkey', 'Mouth', 'Map', 'Mask', 'Music','Man'],
    N: ['Nest', 'Net', 'Night', 'Nurse', 'Nose', 'Neck', 'Note', 'Nine', 'Name', 'Nap', 'North','Nigeria'],
    O: ['Orange', 'Owl', 'Ocean', 'Orbit', 'Office', 'Oak', 'Oil', 'Old', 'Open', 'Onion', 'Ostrich','Antelope'],
    P: ['Pig', 'Pencil', 'Panda', 'Pizza', 'Parrot', 'Pear', 'Pen', 'Park', 'Plant', 'Pool', 'Puppy','Planet'],
    Q: ['Queen', 'Qoute', 'Quarter', 'Question', 'Quiet', 'Quick', 'Quack', 'Quilt', 'Quail', 'Quartz', 'Quiz','Quiver'],
    R: ['Robot', 'Rabbit', 'Rainbow', 'Rose', 'Rocket', 'Rain', 'Red', 'Ring', 'River', 'Road', 'Rock','Roll'],
    S: ['Sun', 'Star', 'Sister', 'Spider', 'Ship', 'Snake', 'Snow', 'Sock', 'Soup', 'Spoon', 'Smile','Sound'],
    T: ['Tree', 'Train', 'Tiger', 'Turtle', 'Table', 'Tent', 'Tea', 'Tiger', 'Toast', 'Toy', 'Truck','Trust'],
    U: ['Unique', 'Unicorn', 'Up', 'Umpire', 'Uncle', 'Unit', 'Urn', 'Us', 'Under', 'Urban', 'User','Universe'],
    V: ['Van', 'Vacuum', 'Velvet', 'Voice', 'Village', 'Vase', 'Vest', 'Vine', 'View', 'Vast', 'Vintage','Vantage'],
    W: ['Water', 'Window', 'Wolf', 'Watch', 'Whale', 'Wagon', 'Wall', 'Wave', 'Web', 'Wind', 'Wing','Wisdom'],
    X: ['X-ray', 'Xylophone', 'Xenon', 'Xerox', 'Xeric', 'X-axis', 'Xis', 'Xenon', 'X-factor', 'Xenon', 'Xylem'],
    Y: ['Yellow', 'Yoyo', 'Yacht', 'Yak', 'Yogurt', 'Yard', 'Yarn', 'Yawn', 'Year', 'Yell', 'Yolk','Yes'],
    Z: ['Zebra', 'Zoo', 'Zipper', 'Zero', 'Zigzag', 'Zest', 'Zinc', 'Zone', 'Zoom', 'Zion', 'Zany','Zeal']
};
