export const AlphabetWords = {
    A: ['Apple', 'Ant', 'Airplane', 'Arrow', 'Artist'],
    B: ['Ball', 'Bear', 'Banana', 'Book', 'Balloon'],
    C: ['Cat', 'Coding', 'Cake', 'Candy', 'Cabin'],
    D: ['Dog', 'Door', 'Duck', 'Dolphin', 'Daddy'],
    E: ['Echo', 'Eagle', 'Egg', 'Eye', 'Earth'],
    F: ['Fish', 'Flower', 'Friend', 'Flag', 'Fire'],
    G: ['Garment', 'Goat', 'Guitar', 'Glass', 'Garden'],
    H: ['Horse', 'House', 'Hat', 'Heart', 'Hand'],
    I: ['Ice', 'Island', 'Image', 'Ink', 'Iron'],
    J: ['Jam', 'Juice', 'Jockey', 'Jacket', 'Jungle'],
    K: ['King', 'Kite', 'Keyboard', 'Key', 'Kitchen'],
    L: ['Lion', 'Lamp', 'Leaf', 'Lemon', 'Ladder'],
    M: ['Moon', 'Mum', 'Mouse', 'Mango', 'Magic'],
    N: ['Nest', 'Net', 'Night', 'Nurse', 'Nose'],
    O: ['Orange', 'Owl', 'Ocean', 'Orbit', 'Office'],
    P: ['Pig', 'Pencil', 'Panda', 'Pizza', 'Parrot'],
    Q: ['Queen', 'Qoute', 'Quarter', 'Question', 'Quiet'],
    R: ['Robot', 'Rabbit', 'Rainbow', 'Rose', 'Rocket'],
    S: ['Sun', 'Star', 'Sister', 'Spider', 'Ship'],
    T: ['Tree', 'Train', 'Tiger', 'Turtle', 'Table'],
    U: ['Unique', 'Unicorn', 'Up', 'Umpire', 'Uncle'],
    V: ['Van', 'Vacuum', 'Velvet', 'Voice', 'Village'],
    W: ['Water', 'Window', 'Wolf', 'Watch', 'Whale'],
    X: ['Xyster', 'X-ray', 'Xenon', 'Xenon', 'Xylene'],
    Y: ['Yellow', 'Yoyo', 'Yacht', 'Yak', 'Yogurt'],
    Z: ['Zebra', 'Zoo', 'Zipper', 'Zero', 'Zigzag']
};